version: "3.9"
services:
  backend:
    build: ./backend
    container_name: appsking_backend
    environment:
      - NODE_ENV=production
      - PORT=5001
      - DB_HOST=
      - DB_PORT=3306
      - DB_USER=
      - DB_PASSWORD=
      - DB_NAME=
      - JWT_SECRET=
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - backend_uploads:/app/uploads
    ports:
      - "5001:5001"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: appsking_frontend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:5001/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_uploads:
